/**
 * School Master
 * This Postman collection contains all API endpoints for developing School Master projects.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body4 {
  new_password1: string;
  new_password2: string;
  token: string;
  uid: string;
}
