/**
 * School Master
 * This Postman collection contains all API endpoints for developing School Master projects.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body5 {
  email: string;
  first_name: string;
  last_name: string;
  password1: string;
  password2: string;
  phone_number: string;
  post_code: string;
}
